### ISSUE TITLE
Uncatchable PresentationFramework.Aero2

### ISSUE THREAD

**Issue by smad2005** [smad2005/PathOfExileStashSorter#4]
```
문제 서명:
문제 이벤트 이름: CLR20r3
문제 서명 01: POEStashSorter.exe
문제 서명 02: 1.0.0.0
문제 서명 03: 56100335
문제 서명 04: PresentationFramework
문제 서명 05: 4.6.81.0
문제 서명 06: 5584f3d7
문제 서명 07: 21de
문제 서명 08: f6
문제 서명 09: System.Windows.Markup.XamlParse
OS 버전: 6.1.7601.2.1.0.256.1
로캘 ID: 1042
추가 정보 1: 0a9e
추가 정보 2: 0a9e372d3b4ad19135b953a78882e789
추가 정보 3: 0a9e
추가 정보 4: 0a9e372d3b4ad19135b953a78882e789
```

```
'Set property 'System.Windows.ResourceDictionary.DeferrableContent' threw an exception.' Line number '108' and line position '18'. at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
at POEStashSorter.MainWindow.InitializeComponent()
at POEStashSorter.MainWindow..ctor()
at POEStashSorter.LoginWindow.btnLogin_Click(Object sender, RoutedEventArgs e)
```

```
"Could not load file or assembly 'PresentationFramework.Aero2, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Reference assemblies should not be loaded for execution. They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x8013105"
```

**Comment by smad2005** [comment]
Reproduced on windows 7. `PresentationFramework.Aero2.dll`  replaced by `PresentationFramework.AeroLite.dll`
